# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eRQf_QEJ7Mrb4nvMZLcjdw7dpLTbbj-U
"""

# Digital Image Processing Mini Project
# Noise Removal and Object Segmentation

import cv2
import numpy as np
import matplotlib.pyplot as plt

from skimage.metrics import mean_squared_error
from skimage.metrics import peak_signal_noise_ratio
from skimage.metrics import structural_similarity

# Install/Import required library
import torch
from torchvision.datasets import OxfordIIITPet

# Download Oxford-IIIT Pet dataset
dataset = OxfordIIITPet(
    root="/content/pet_dataset",
    target_types="segmentation",
    download=True
)

print("Dataset downloaded successfully!")
print("Number of images:", len(dataset))

import matplotlib.pyplot as plt

# Select the first image
image, mask = dataset[0]

# Display image and segmentation mask
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.imshow(image)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(mask)
plt.title("Ground Truth Segmentation")
plt.axis("off")

plt.show()

# Convert the original image to a NumPy array
image_np = np.array(image)

# Convert RGB image to grayscale
gray_image = cv2.cvtColor(image_np, cv2.COLOR_RGB2GRAY)

# Display grayscale image
plt.figure(figsize=(6, 5))

plt.imshow(gray_image, cmap="gray")
plt.title("Grayscale Image")
plt.axis("off")

plt.show()

# Generate Gaussian noise
mean = 0
sigma = 25

gaussian_noise = np.random.normal(
    mean,
    sigma,
    gray_image.shape
)

# Add Gaussian noise to the grayscale image
gaussian_noisy = gray_image.astype(np.float32) + gaussian_noise

# Keep pixel values between 0 and 255
gaussian_noisy = np.clip(gaussian_noisy, 0, 255)

# Convert back to uint8
gaussian_noisy = gaussian_noisy.astype(np.uint8)

# Display original and Gaussian noisy image
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.imshow(gray_image, cmap="gray")
plt.title("Original Grayscale Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(gaussian_noisy, cmap="gray")
plt.title("Gaussian Noisy Image")
plt.axis("off")

plt.show()

# Create a copy of the grayscale image
salt_pepper_noisy = gray_image.copy()

# Amount of noise
noise_amount = 0.05

# Total number of pixels
total_pixels = gray_image.size

# Number of noisy pixels
num_noisy_pixels = int(noise_amount * total_pixels)

# Add salt noise (white pixels)
salt_coords = (
    np.random.randint(0, gray_image.shape[0], num_noisy_pixels),
    np.random.randint(0, gray_image.shape[1], num_noisy_pixels)
)

salt_pepper_noisy[salt_coords] = 255

# Add pepper noise (black pixels)
pepper_coords = (
    np.random.randint(0, gray_image.shape[0], num_noisy_pixels),
    np.random.randint(0, gray_image.shape[1], num_noisy_pixels)
)

salt_pepper_noisy[pepper_coords] = 0

# Display the noisy image
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.imshow(gray_image, cmap="gray")
plt.title("Original Grayscale Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(salt_pepper_noisy, cmap="gray")
plt.title("Salt-and-Pepper Noisy Image")
plt.axis("off")

plt.show()

# Apply 7 × 7 Mean Filter
gaussian_mean = cv2.blur(gaussian_noisy, (7, 7))
salt_pepper_mean = cv2.blur(salt_pepper_noisy, (7, 7))

# Apply 7 × 7 Median Filter
gaussian_median = cv2.medianBlur(gaussian_noisy, 7)
salt_pepper_median = cv2.medianBlur(salt_pepper_noisy, 7)

# Display restoration results
plt.figure(figsize=(14, 10))

# Gaussian noise
plt.subplot(2, 3, 1)
plt.imshow(gaussian_noisy, cmap="gray")
plt.title("Gaussian Noisy")
plt.axis("off")

plt.subplot(2, 3, 2)
plt.imshow(gaussian_mean, cmap="gray")
plt.title("Gaussian + Mean Filter")
plt.axis("off")

plt.subplot(2, 3, 3)
plt.imshow(gaussian_median, cmap="gray")
plt.title("Gaussian + Median Filter")
plt.axis("off")

# Salt-and-pepper noise
plt.subplot(2, 3, 4)
plt.imshow(salt_pepper_noisy, cmap="gray")
plt.title("Salt-and-Pepper Noisy")
plt.axis("off")

plt.subplot(2, 3, 5)
plt.imshow(salt_pepper_mean, cmap="gray")
plt.title("S&P + Mean Filter")
plt.axis("off")

plt.subplot(2, 3, 6)
plt.imshow(salt_pepper_median, cmap="gray")
plt.title("S&P + Median Filter")
plt.axis("off")

plt.tight_layout()
plt.show()

from skimage.metrics import mean_squared_error
from skimage.metrics import peak_signal_noise_ratio
from skimage.metrics import structural_similarity

# Function to calculate evaluation metrics
def calculate_metrics(original, restored):
    mse = mean_squared_error(original, restored)
    psnr = peak_signal_noise_ratio(original, restored, data_range=255)
    ssim = structural_similarity(original, restored, data_range=255)

    return mse, psnr, ssim


# Gaussian Noise Results
gaussian_mean_metrics = calculate_metrics(gray_image, gaussian_mean)
gaussian_median_metrics = calculate_metrics(gray_image, gaussian_median)

# Salt-and-Pepper Noise Results
sp_mean_metrics = calculate_metrics(gray_image, salt_pepper_mean)
sp_median_metrics = calculate_metrics(gray_image, salt_pepper_median)


# Display results
print("GAUSSIAN NOISE")
print("-----------------------------")
print("Mean Filter")
print("MSE  :", gaussian_mean_metrics[0])
print("PSNR :", gaussian_mean_metrics[1])
print("SSIM :", gaussian_mean_metrics[2])

print("\nMedian Filter")
print("MSE  :", gaussian_median_metrics[0])
print("PSNR :", gaussian_median_metrics[1])
print("SSIM :", gaussian_median_metrics[2])


print("\nSALT-AND-PEPPER NOISE")
print("-----------------------------")
print("Mean Filter")
print("MSE  :", sp_mean_metrics[0])
print("PSNR :", sp_mean_metrics[1])
print("SSIM :", sp_mean_metrics[2])

print("\nMedian Filter")
print("MSE  :", sp_median_metrics[0])
print("PSNR :", sp_median_metrics[1])
print("SSIM :", sp_median_metrics[2])

# Apply Otsu's thresholding
otsu_threshold, otsu_segmented = cv2.threshold(
    salt_pepper_median,
    0,
    255,
    cv2.THRESH_BINARY + cv2.THRESH_OTSU
)

# Display the restored image and Otsu segmentation
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.imshow(salt_pepper_median, cmap="gray")
plt.title("Restored Image - Median Filter")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(otsu_segmented, cmap="gray")
plt.title("Otsu Segmented Image")
plt.axis("off")

plt.show()

# Display the optimal threshold value
print("Optimal Otsu Threshold Value:", otsu_threshold)

# Create a morphological kernel
kernel = np.ones((5, 5), np.uint8)

# Apply morphological opening
opened = cv2.morphologyEx(
    otsu_segmented,
    cv2.MORPH_OPEN,
    kernel
)

# Apply morphological closing
morphology_result = cv2.morphologyEx(
    opened,
    cv2.MORPH_CLOSE,
    kernel
)

# Display the results
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.imshow(otsu_segmented, cmap="gray")
plt.title("Otsu Segmentation")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(opened, cmap="gray")
plt.title("After Opening")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(morphology_result, cmap="gray")
plt.title("After Opening + Closing")
plt.axis("off")

plt.tight_layout()
plt.show()

# Convert the ground-truth mask to a NumPy array
mask_np = np.array(mask)

# Display unique values in the ground-truth mask
print("Unique values in ground-truth mask:")
print(np.unique(mask_np))

# Display the ground-truth mask
plt.figure(figsize=(6, 5))
plt.imshow(mask_np, cmap="gray")
plt.title("Ground Truth Segmentation Mask")
plt.axis("off")
plt.show()

# Convert ground-truth mask into binary form
# In Oxford-IIIT Pet, label 1 represents the pet
ground_truth = (mask_np == 1).astype(np.uint8)

# Convert our segmentation result into binary form
predicted = (morphology_result > 0).astype(np.uint8)

# Calculate Intersection and Union
intersection = np.logical_and(
    ground_truth,
    predicted
).sum()

union = np.logical_or(
    ground_truth,
    predicted
).sum()

# Calculate IoU
iou = intersection / union

# Calculate Dice Score
dice = (2 * intersection) / (
    ground_truth.sum() + predicted.sum()
)

print("Segmentation Evaluation")
print("-----------------------------")
print("IoU Score  :", iou)
print("Dice Score :", dice)

plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.imshow(mask_np, cmap="gray")
plt.title("Ground Truth Mask")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(otsu_segmented, cmap="gray")
plt.title("Otsu Segmentation")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(morphology_result, cmap="gray")
plt.title("Final Segmentation")
plt.axis("off")

plt.tight_layout()
plt.show()

# Apply Canny Edge Detection
edges = cv2.Canny(
    salt_pepper_median,
    50,
    150
)

# Display the results
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.imshow(salt_pepper_median, cmap="gray")
plt.title("Restored Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(edges, cmap="gray")
plt.title("Canny Edge Detection")
plt.axis("off")

plt.tight_layout()
plt.show()

plt.figure(figsize=(16, 10))

plt.subplot(2, 3, 1)
plt.imshow(gray_image, cmap="gray")
plt.title("Original Grayscale")
plt.axis("off")

plt.subplot(2, 3, 2)
plt.imshow(gaussian_noisy, cmap="gray")
plt.title("Gaussian Noise")
plt.axis("off")

plt.subplot(2, 3, 3)
plt.imshow(salt_pepper_noisy, cmap="gray")
plt.title("Salt-and-Pepper Noise")
plt.axis("off")

plt.subplot(2, 3, 4)
plt.imshow(salt_pepper_median, cmap="gray")
plt.title("Median Filtered Image")
plt.axis("off")

plt.subplot(2, 3, 5)
plt.imshow(morphology_result, cmap="gray")
plt.title("Otsu + Morphological Segmentation")
plt.axis("off")

plt.subplot(2, 3, 6)
plt.imshow(edges, cmap="gray")
plt.title("Canny Edge Detection")
plt.axis("off")

plt.tight_layout()
plt.show()

# Number of images to evaluate
num_images = 20

# Lists to store results
mse_results = []
psnr_results = []
ssim_results = []
iou_results = []
dice_results = []

for i in range(num_images):

    # Get image and ground-truth mask
    image, mask = dataset[i]

    # Convert image to NumPy
    image_np = np.array(image)

    # Convert RGB to grayscale
    gray = cv2.cvtColor(image_np, cv2.COLOR_RGB2GRAY)

    # -----------------------------
    # Add Salt-and-Pepper Noise
    # -----------------------------
    noisy = gray.copy()

    noise_amount = 0.05
    total_pixels = gray.size
    num_noisy_pixels = int(noise_amount * total_pixels)

    # Salt
    salt_coords = (
        np.random.randint(0, gray.shape[0], num_noisy_pixels),
        np.random.randint(0, gray.shape[1], num_noisy_pixels)
    )
    noisy[salt_coords] = 255

    # Pepper
    pepper_coords = (
        np.random.randint(0, gray.shape[0], num_noisy_pixels),
        np.random.randint(0, gray.shape[1], num_noisy_pixels)
    )
    noisy[pepper_coords] = 0

    # -----------------------------
    # Median Filtering
    # -----------------------------
    restored = cv2.medianBlur(noisy, 7)

    # -----------------------------
    # Restoration Metrics
    # -----------------------------
    mse = mean_squared_error(gray, restored)
    psnr = peak_signal_noise_ratio(
        gray,
        restored,
        data_range=255
    )
    ssim = structural_similarity(
        gray,
        restored,
        data_range=255
    )

    mse_results.append(mse)
    psnr_results.append(psnr)
    ssim_results.append(ssim)

    # -----------------------------
    # Otsu Segmentation
    # -----------------------------
    _, segmented = cv2.threshold(
        restored,
        0,
        255,
        cv2.THRESH_BINARY + cv2.THRESH_OTSU
    )

    # Morphological processing
    kernel = np.ones((5, 5), np.uint8)

    opened = cv2.morphologyEx(
        segmented,
        cv2.MORPH_OPEN,
        kernel
    )

    final_segmentation = cv2.morphologyEx(
        opened,
        cv2.MORPH_CLOSE,
        kernel
    )

    # -----------------------------
    # Ground Truth
    # -----------------------------
    mask_np = np.array(mask)

    ground_truth = (mask_np == 1).astype(np.uint8)
    predicted = (final_segmentation > 0).astype(np.uint8)

    # -----------------------------
    # IoU and Dice
    # -----------------------------
    intersection = np.logical_and(
        ground_truth,
        predicted
    ).sum()

    union = np.logical_or(
        ground_truth,
        predicted
    ).sum()

    if union > 0:
        iou = intersection / union
    else:
        iou = 0

    denominator = ground_truth.sum() + predicted.sum()

    if denominator > 0:
        dice = (2 * intersection) / denominator
    else:
        dice = 0

    iou_results.append(iou)
    dice_results.append(dice)


# -----------------------------
# Calculate Average Results
# -----------------------------

print("AVERAGE RESULTS FOR", num_images, "IMAGES")
print("------------------------------------------")

print("Average MSE  :", np.mean(mse_results))
print("Average PSNR :", np.mean(psnr_results))
print("Average SSIM :", np.mean(ssim_results))

print("\nSegmentation Results")
print("------------------------------------------")

print("Average IoU   :", np.mean(iou_results))
print("Average Dice  :", np.mean(dice_results))

import matplotlib.pyplot as plt

# Restoration metrics
restoration_metrics = ["MSE", "PSNR", "SSIM"]
restoration_values = [
    np.mean(mse_results),
    np.mean(psnr_results),
    np.mean(ssim_results)
]

# Segmentation metrics
segmentation_metrics = ["IoU", "Dice"]
segmentation_values = [
    np.mean(iou_results),
    np.mean(dice_results)
]

# -----------------------------
# Restoration Results Graph
# -----------------------------
plt.figure(figsize=(8, 5))

plt.bar(restoration_metrics, restoration_values)

plt.title("Average Restoration Results - 20 Images")
plt.xlabel("Metrics")
plt.ylabel("Average Value")

plt.show()


# -----------------------------
# Segmentation Results Graph
# -----------------------------
plt.figure(figsize=(8, 5))

plt.bar(segmentation_metrics, segmentation_values)

plt.title("Average Segmentation Results - 20 Images")
plt.xlabel("Metrics")
plt.ylabel("Average Score")

plt.ylim(0, 1)

plt.show()